"""Add game column to servers and seed Retail realms.

Revision ID: 020
Revises: 019
Create Date: 2026-04-XX
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "020"
down_revision = "019"
branch_labels = None
depends_on = None

_EU_RETAIL: list[tuple[str, str]] = [
    ("Aegwynn", "EU"),
    ("Aerie Peak", "EU"),
    ("Agamaggan", "EU"),
    ("Aggra", "EU"),
    ("Aggramar", "EU"),
    ("Ahn'Qiraj", "EU"),
    ("Al'Akir", "EU"),
    ("Alexstrasza", "EU"),
    ("Alleria", "EU"),
    ("Alonsus", "EU"),
    ("Aman'Thul", "EU"),
    ("Ambossar", "EU"),
    ("Anachronos", "EU"),
    ("Anetheron", "EU"),
    ("Antonidas", "EU"),
    ("Anub'arak", "EU"),
    ("Arak-arahm", "EU"),
    ("Arathi", "EU"),
    ("Arathor", "EU"),
    ("Archimonde", "EU"),
    ("Area 52", "EU"),
    ("Argent Dawn", "EU"),
    ("Arthas", "EU"),
    ("Arygos", "EU"),
    ("Aszune", "EU"),
    ("Auchindoun", "EU"),
    ("Azjol-Nerub", "EU"),
    ("Azshara", "EU"),
    ("Azuremyst", "EU"),
    ("Baelgun", "EU"),
    ("Balnazzar", "EU"),
    ("Blackhand", "EU"),
    ("Blackmoore", "EU"),
    ("Blackrock", "EU"),
    ("Blade's Edge", "EU"),
    ("Bladefist", "EU"),
    ("Bloodfeather", "EU"),
    ("Bloodhoof", "EU"),
    ("Bloodscalp", "EU"),
    ("Blutkessel", "EU"),
    ("Boulderfist", "EU"),
    ("Bronze Dragonflight", "EU"),
    ("Bronzebeard", "EU"),
    ("Burning Blade", "EU"),
    ("Burning Legion", "EU"),
    ("Burning Steppes", "EU"),
    ("C'Thun", "EU"),
    ("Chamber of Aspects", "EU"),
    ("Chants éternels", "EU"),
    ("Cho'gall", "EU"),
    ("Chromaggus", "EU"),
    ("Colinas Pardas", "EU"),
    ("Confrérie du Thorium", "EU"),
    ("Conseil des Ombres", "EU"),
    ("Crushridge", "EU"),
    ("Cultedela Rivenoire", "EU"),
    ("Daggerspine", "EU"),
    ("Dalaran", "EU"),
    ("Dalvengyr", "EU"),
    ("Darkmoon Faire", "EU"),
    ("Darksorrow", "EU"),
    ("Darkspear", "EU"),
    ("Das Konsortium", "EU"),
    ("Das Syndikat", "EU"),
    ("Deathwing", "EU"),
    ("Defias Brotherhood", "EU"),
    ("Dentarg", "EU"),
    ("Der abyssische Rat", "EU"),
    ("Der Mithrilorden", "EU"),
    ("Der Rat von Dalaran", "EU"),
    ("Destromath", "EU"),
    ("Dethecus", "EU"),
    ("Die Aldor", "EU"),
    ("Die Arguswacht", "EU"),
    ("Die ewige Wacht", "EU"),
    ("Die Nachtwache", "EU"),
    ("Die Silberne Hand", "EU"),
    ("Die Todeskrallen", "EU"),
    ("Doomhammer", "EU"),
    ("Draenor", "EU"),
    ("Dragonblight", "EU"),
    ("Dragonmaw", "EU"),
    ("Drak'thul", "EU"),
    ("Drek'Thar", "EU"),
    ("Dun Modr", "EU"),
    ("Dun Morogh", "EU"),
    ("Dunemaul", "EU"),
    ("Durotan", "EU"),
    ("Earthen Ring", "EU"),
    ("Echsenkessel", "EU"),
    ("Eitrigg", "EU"),
    ("Eldre'Thalas", "EU"),
    ("Elune", "EU"),
    ("Emerald Dream", "EU"),
    ("Emeriss", "EU"),
    ("Eonar", "EU"),
    ("Eredar", "EU"),
    ("Executus", "EU"),
    ("Exodar", "EU"),
    ("Festung der Stürme", "EU"),
    ("Forscherliga", "EU"),
    ("Frostmane", "EU"),
    ("Frostmourne", "EU"),
    ("Frostwhisper", "EU"),
    ("Frostwolf", "EU"),
    ("Garona", "EU"),
    ("Garrosh", "EU"),
    ("Genjuros", "EU"),
    ("Ghostlands", "EU"),
    ("Gilneas", "EU"),
    ("Gorgonnash", "EU"),
    ("Grim Batol", "EU"),
    ("Gul'dan", "EU"),
    ("Hakkar", "EU"),
    ("Haomarush", "EU"),
    ("Hellfire", "EU"),
    ("Hellscream", "EU"),
    ("Hyjal", "EU"),
    ("Illidan", "EU"),
    ("Jaedenar", "EU"),
    ("Kael'Thas", "EU"),
    ("Karazhan", "EU"),
    ("Kargath", "EU"),
    ("Kazzak", "EU"),
    ("Kel'Thuzad", "EU"),
    ("Khadgar", "EU"),
    ("Khaz Modan", "EU"),
    ("Khaz'goroth", "EU"),
    ("Kil'Jaeden", "EU"),
    ("Kilrogg", "EU"),
    ("Kirin Tor", "EU"),
    ("Kor'gall", "EU"),
    ("Krag'jin", "EU"),
    ("Krasus", "EU"),
    ("Kul Tiras", "EU"),
    ("Kult  der Verdammten", "EU"),
    ("La Croisade écarlate", "EU"),
    ("Laughing Skull", "EU"),
    ("Les Clairvoyants", "EU"),
    ("Les Sentinelles", "EU"),
    ("Lightbringer", "EU"),
    ("Lightning's Blade", "EU"),
    ("Lordaeron", "EU"),
    ("Los Errantes", "EU"),
    ("Lothar", "EU"),
    ("Madmortem", "EU"),
    ("Magtheridon", "EU"),
    ("Mal'Ganis", "EU"),
    ("Malfurion", "EU"),
    ("Malorne", "EU"),
    ("Malygos", "EU"),
    ("Mannoroth", "EU"),
    ("Marécagede Zangar", "EU"),
    ("Mazrigos", "EU"),
    ("Medivh", "EU"),
    ("Minahonda", "EU"),
    ("Moonglade", "EU"),
    ("Mug'thol", "EU"),
    ("Nagrand", "EU"),
    ("Nathrezim", "EU"),
    ("Naxxramas", "EU"),
    ("Nazjatar", "EU"),
    ("Nefarian", "EU"),
    ("Nemesis", "EU"),
    ("Neptulon", "EU"),
    ("Ner'zhul", "EU"),
    ("Nera'thor", "EU"),
    ("Nethersturm", "EU"),
    ("Nordrassil", "EU"),
    ("Norgannon", "EU"),
    ("Nozdormu", "EU"),
    ("Onyxia", "EU"),
    ("Outland", "EU"),
    ("Perenolde", "EU"),
    ("Pozzo dell'Eternità", "EU"),
    ("Proudmoore", "EU"),
    ("Quel'Thalas", "EU"),
    ("Ragnaros", "EU"),
    ("Rajaxx", "EU"),
    ("Rashgarroth", "EU"),
    ("Ravencrest", "EU"),
    ("Ravenholdt", "EU"),
    ("Rexxar", "EU"),
    ("Runetotem", "EU"),
    ("Sanguino", "EU"),
    ("Sargeras", "EU"),
    ("Saurfang", "EU"),
    ("Scarshield Legion", "EU"),
    ("Sen'jin", "EU"),
    ("Shadowsong", "EU"),
    ("Shattered Halls", "EU"),
    ("Shattered Hand", "EU"),
    ("Shattrath", "EU"),
    ("Shen'dralar", "EU"),
    ("Silvermoon", "EU"),
    ("Sinstralis", "EU"),
    ("Skullcrusher", "EU"),
    ("Spinebreaker", "EU"),
    ("Sporeggar", "EU"),
    ("Steamwheedle Cartel", "EU"),
    ("Stormrage", "EU"),
    ("Stormreaver", "EU"),
    ("Stormscale", "EU"),
    ("Sunstrider", "EU"),
    ("Suramar", "EU"),
    ("Sylvanas", "EU"),
    ("Taerar", "EU"),
    ("Talnivarr", "EU"),
    ("Tarren Mill", "EU"),
    ("Teldrassil", "EU"),
    ("Templenoir", "EU"),
    ("Terenas", "EU"),
    ("Terokkar", "EU"),
    ("Terrordar", "EU"),
    ("The Maelstrom", "EU"),
    ("The Sha'tar", "EU"),
    ("The Venture Co.", "EU"),
    ("Theradras", "EU"),
    ("Thrall", "EU"),
    ("Throk'Feroth", "EU"),
    ("Thunderhorn", "EU"),
    ("Tichondrius", "EU"),
    ("Tirion", "EU"),
    ("Todeswache", "EU"),
    ("Trollbane", "EU"),
    ("Turalyon", "EU"),
    ("Twilight's Hammer", "EU"),
    ("Twisting Nether", "EU"),
    ("Tyrande", "EU"),
    ("Uldaman", "EU"),
    ("Ulduar", "EU"),
    ("Uldum", "EU"),
    ("Un'Goro", "EU"),
    ("Varimathras", "EU"),
    ("Vashj", "EU"),
    ("Vek'lor", "EU"),
    ("Vek'nilash", "EU"),
    ("Vol'jin", "EU"),
    ("Well of Eternity", "EU"),
    ("Wildhammer", "EU"),
    ("Wrathbringer", "EU"),
    ("Xavius", "EU"),
    ("Ysera", "EU"),
    ("Ysondre", "EU"),
    ("Zenedar", "EU"),
    ("Zirkel des Cenarius", "EU"),
    ("Zul'Jin", "EU"),
    ("Zuluhed", "EU"),
]

_US_RETAIL: list[tuple[str, str]] = [
    ("Aegwynn", "US"),
    ("Aerie Peak", "US"),
    ("Agamaggan", "US"),
    ("Aggramar", "US"),
    ("Akama", "US"),
    ("Alexstrasza", "US"),
    ("Alleria", "US"),
    ("Altar of Storms", "US"),
    ("Alterac Mountains", "US"),
    ("Andorhal", "US"),
    ("Anetheron", "US"),
    ("Antonidas", "US"),
    ("Anub'arak", "US"),
    ("Anvilmar", "US"),
    ("Arathor", "US"),
    ("Archimonde", "US"),
    ("Area 52", "US"),
    ("Argent Dawn", "US"),
    ("Arthas", "US"),
    ("Arygos", "US"),
    ("Auchindoun", "US"),
    ("Azgalor", "US"),
    ("Azjol-Nerub", "US"),
    ("Azralon", "US"),
    ("Azshara", "US"),
    ("Azuremyst", "US"),
    ("Baelgun", "US"),
    ("Balnazzar", "US"),
    ("Black Dragonflight", "US"),
    ("Blackhand", "US"),
    ("Blackrock", "US"),
    ("Blackwater Raiders", "US"),
    ("Blackwing Lair", "US"),
    ("Blade's Edge", "US"),
    ("Bladefist", "US"),
    ("Bleeding Hollow", "US"),
    ("Blood Furnace", "US"),
    ("Bloodhoof", "US"),
    ("Bloodscalp", "US"),
    ("Bonechewer", "US"),
    ("Borean Tundra", "US"),
    ("Boulderfist", "US"),
    ("Bronzebeard", "US"),
    ("Burning Blade", "US"),
    ("Burning Legion", "US"),
    ("Cairne", "US"),
    ("Cenarion Circle", "US"),
    ("Cenarius", "US"),
    ("Cho'gall", "US"),
    ("Chromaggus", "US"),
    ("Coilfang", "US"),
    ("Crushridge", "US"),
    ("Daggerspine", "US"),
    ("Dalaran", "US"),
    ("Dalvengyr", "US"),
    ("Dark Iron", "US"),
    ("Darkspear", "US"),
    ("Darrowmere", "US"),
    ("Dawnbringer", "US"),
    ("Deathwing", "US"),
    ("Demon Soul", "US"),
    ("Dentarg", "US"),
    ("Destromath", "US"),
    ("Dethecus", "US"),
    ("Detheroc", "US"),
    ("Doomhammer", "US"),
    ("Draenor", "US"),
    ("Dragonblight", "US"),
    ("Dragonmaw", "US"),
    ("Drak'Tharon", "US"),
    ("Drak'thul", "US"),
    ("Draka", "US"),
    ("Drakkari", "US"),
    ("Drenden", "US"),
    ("Dunemaul", "US"),
    ("Durotan", "US"),
    ("Duskwood", "US"),
    ("Earthen Ring", "US"),
    ("Echo Isles", "US"),
    ("Eitrigg", "US"),
    ("Eldre'Thalas", "US"),
    ("Elune", "US"),
    ("Emerald Dream", "US"),
    ("Eonar", "US"),
    ("Eredar", "US"),
    ("Executus", "US"),
    ("Exodar", "US"),
    ("Farstriders", "US"),
    ("Feathermoon", "US"),
    ("Fenris", "US"),
    ("Firetree", "US"),
    ("Fizzcrank", "US"),
    ("Frostmane", "US"),
    ("Frostwolf", "US"),
    ("Galakrond", "US"),
    ("Gallywix", "US"),
    ("Garithos", "US"),
    ("Garona", "US"),
    ("Garrosh", "US"),
    ("Ghostlands", "US"),
    ("Gilneas", "US"),
    ("Gnomeregan", "US"),
    ("Goldrinn", "US"),
    ("Gorefiend", "US"),
    ("Gorgonnash", "US"),
    ("Greymane", "US"),
    ("Grizzly Hills", "US"),
    ("Gul'dan", "US"),
    ("Gurubashi", "US"),
    ("Hakkar", "US"),
    ("Haomarush", "US"),
    ("Hellscream", "US"),
    ("Hydraxis", "US"),
    ("Hyjal", "US"),
    ("Icecrown", "US"),
    ("Illidan", "US"),
    ("Jaedenar", "US"),
    ("Kael'thas", "US"),
    ("Kalecgos", "US"),
    ("Kargath", "US"),
    ("Kel'Thuzad", "US"),
    ("Khadgar", "US"),
    ("Khaz Modan", "US"),
    ("Kil'Jaeden", "US"),
    ("Kilrogg", "US"),
    ("Kirin Tor", "US"),
    ("Korgath", "US"),
    ("Korialstrasz", "US"),
    ("KulTiras", "US"),
    ("Laughing Skull", "US"),
    ("Lethon", "US"),
    ("Lightbringer", "US"),
    ("Lightning's Blade", "US"),
    ("Lightninghoof", "US"),
    ("Llane", "US"),
    ("Lothar", "US"),
    ("Madoran", "US"),
    ("Maelstrom", "US"),
    ("Magtheridon", "US"),
    ("Maiev", "US"),
    ("Mal'Ganis", "US"),
    ("Malfurion", "US"),
    ("Malorne", "US"),
    ("Malygos", "US"),
    ("Mannoroth", "US"),
    ("Medivh", "US"),
    ("Misha", "US"),
    ("Mok'Nathal", "US"),
    ("Moon Guard", "US"),
    ("Moonrunner", "US"),
    ("Mug'thol", "US"),
    ("Muradin", "US"),
    ("Nathrezim", "US"),
    ("Nazgrel", "US"),
    ("Nazjatar", "US"),
    ("Nemesis", "US"),
    ("Ner'zhul", "US"),
    ("Nesingwary", "US"),
    ("Nordrassil", "US"),
    ("Norgannon", "US"),
    ("Onyxia", "US"),
    ("Perenolde", "US"),
    ("Proudmoore", "US"),
    ("Quel'dorei", "US"),
    ("Quel’Thalas", "US"),
    ("Ragnaros", "US"),
    ("Ravencrest", "US"),
    ("Ravenholdt", "US"),
    ("Rexxar", "US"),
    ("Rivendare", "US"),
    ("Runetotem", "US"),
    ("Sargeras", "US"),
    ("Scarlet Crusade", "US"),
    ("Scilla", "US"),
    ("Sen'Jin", "US"),
    ("Sentinels", "US"),
    ("Shadow Council", "US"),
    ("Shadowmoon", "US"),
    ("Shadowsong", "US"),
    ("Shandris", "US"),
    ("Shattered Halls", "US"),
    ("Shattered Hand", "US"),
    ("Shu'halo", "US"),
    ("Silver Hand", "US"),
    ("Silvermoon", "US"),
    ("Sisters of Elune", "US"),
    ("Skullcrusher", "US"),
    ("Skywall", "US"),
    ("Smolderthorn", "US"),
    ("Spinebreaker", "US"),
    ("Spirestone", "US"),
    ("Staghelm", "US"),
    ("Steamwheedle Cartel", "US"),
    ("Stonemaul", "US"),
    ("Stormrage", "US"),
    ("Stormreaver", "US"),
    ("Stormscale", "US"),
    ("Suramar", "US"),
    ("Tanaris", "US"),
    ("Terenas", "US"),
    ("Terokkar", "US"),
    ("The Forgotten Coast", "US"),
    ("The Scryers", "US"),
    ("The Underbog", "US"),
    ("The Venture Co", "US"),
    ("Thorium Brotherhood", "US"),
    ("Thrall", "US"),
    ("Thunderhorn", "US"),
    ("Thunderlord", "US"),
    ("Tichondrius", "US"),
    ("Tol Barad", "US"),
    ("Tortheldrin", "US"),
    ("Trollbane", "US"),
    ("Turalyon", "US"),
    ("Twisting Nether", "US"),
    ("Uldaman", "US"),
    ("Uldum", "US"),
    ("Undermine", "US"),
    ("Ursin", "US"),
    ("Uther", "US"),
    ("Vashj", "US"),
    ("Vek'nilash", "US"),
    ("Velen", "US"),
    ("Warsong", "US"),
    ("Whisperwind", "US"),
    ("WildHammer", "US"),
    ("Windrunner", "US"),
    ("Winterhoof", "US"),
    ("Wyrmrest Accord", "US"),
    ("Ysera", "US"),
    ("Ysondre", "US"),
    ("Zangarmarsh", "US"),
    ("Zul'jin", "US"),
    ("Zuluhed", "US"),
]

_OCE_RETAIL: list[tuple[str, str]] = [
    ("Aman'Thul", "OCE"),
    ("Barthilas", "OCE"),
    ("Caelestrasz", "OCE"),
    ("Dath'Remar", "OCE"),
    ("Dreadmaul", "OCE"),
    ("Frostmourne", "OCE"),
    ("Gundrak", "OCE"),
    ("Jubei'Thos", "OCE"),
    ("Khaz'goroth", "OCE"),
    ("Nagrand", "OCE"),
    ("Saurfang", "OCE"),
    ("Thaurissan", "OCE"),
]

_RU_RETAIL: list[tuple[str, str]] = [
    ("Ashenvale", "RU"),
    ("Azuregos", "RU"),
    ("Blackscar", "RU"),
    ("Booty Bay", "RU"),
    ("Borean Tundra", "RU"),
    ("Deathguard", "RU"),
    ("Deathweaver", "RU"),
    ("Deephome", "RU"),
    ("Eversong", "RU"),
    ("Fordragon", "RU"),
    ("Galakrond", "RU"),
    ("Goldrinn", "RU"),
    ("Gordunni", "RU"),
    ("Greymane", "RU"),
    ("Grom", "RU"),
    ("Howling Fjord", "RU"),
    ("Lich King", "RU"),
    ("Razuvious", "RU"),
    ("Soulflayer", "RU"),
    ("Thermaplugg", "RU"),
]

_RETAIL_ROWS: list[tuple[str, str]] = _EU_RETAIL + _US_RETAIL + _OCE_RETAIL + _RU_RETAIL


_INSERT_RETAIL_SQL = """
INSERT INTO servers (game, name, region, version)
VALUES (:game, :name, :region, :version)
ON CONFLICT (game, name, region, version) DO NOTHING
"""


def upgrade() -> None:
    op.add_column(
        "servers",
        sa.Column("game", sa.Text(), nullable=False, server_default="wow_classic"),
    )

    op.drop_constraint("servers_name_region_version_key", "servers", type_="unique")
    op.create_unique_constraint(
        "servers_game_name_region_version_key",
        "servers",
        ["game", "name", "region", "version"],
    )

    conn = op.get_bind()
    params = [
        {"game": "wow_retail", "name": name, "region": region, "version": "Retail"}
        for name, region in _RETAIL_ROWS
    ]
    conn.execute(sa.text(_INSERT_RETAIL_SQL), params)

    op.alter_column("servers", "game", server_default=None)


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM servers WHERE game = 'wow_retail'"))
    op.drop_constraint("servers_game_name_region_version_key", "servers", type_="unique")
    op.create_unique_constraint(
        "servers_name_region_version_key",
        "servers",
        ["name", "region", "version"],
    )
    op.drop_column("servers", "game")
